
PASSENGER_ID = 3
PASSENGER_EMAIL = 'mirko@gmail.com'
PASSENGER_PASSWORD = 'mirko123'

DRIVER_ID = 6
DRIVER_EMAIL = 'dejan@gmail.com'
DRIVER_PASSWORD = 'dejan123'

ADMIN_ID = 11
ADMIN_EMAIL = 'nole'
ADMIN_PASSWORD = 'novak123'

ACCOUNT_ACTIVATION_ID = 123456
ACCOUNT_ACTIVATION_ID_EXPIRED = 654321
ACCOUNT_ACTIVATION_ID_NON_EXISTING = 123321

PASSWORD_RESET_CODE = 123456
PASSWORD_RESET_CODE_EXPIRED = 123321
PASSWORD_RESET_USER_ID_EXPIRED = 6

RIDE_ID_FOR_MESSAGES = 1

PASSENGER_ATTACHED_TO_RIDE_ID = 3
PASSENGER_ATTACHED_TO_RIDE_EMAIL = 'mirko@gmail.com'

ASSIGNED_DRIVER_PASSWORD = "dejan123"
